<?php

namespace AppBundle\Repository;

/**
 * CategoriaTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
