<?php

namespace AppBundle\Repository;

/**
 * HistorialTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistorialTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
