<?php

namespace AppBundle\Repository;

/**
 * UsuarioCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
